package Model;
// Generated 18/11/2014 01:42:29 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Checkout generated by hbm2java
 */
public class Checkout  implements java.io.Serializable {


     private int codigo;
     private Hospede hospede;
     private Date dataCheckout;

    public Checkout() {
    }

	
    public Checkout(int codigo) {
        this.codigo = codigo;
    }
    public Checkout(int codigo, Hospede hospede, Date dataCheckout) {
       this.codigo = codigo;
       this.hospede = hospede;
       this.dataCheckout = dataCheckout;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Hospede getHospede() {
        return this.hospede;
    }
    
    public void setHospede(Hospede hospede) {
        this.hospede = hospede;
    }
    public Date getDataCheckout() {
        return this.dataCheckout;
    }
    
    public void setDataCheckout(Date dataCheckout) {
        this.dataCheckout = dataCheckout;
    }




}


