package Model;
// Generated 18/11/2014 01:42:29 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Checkin generated by hbm2java
 */
public class Checkin  implements java.io.Serializable {


     private int codigo;
     private Hospede hospede;
     private Date dataCheckin;
     

    public Checkin() {
    }

	
    public Checkin(int codigo) {
        this.codigo = codigo;
    }
    public Checkin(int codigo, Hospede hospede, Date dataCheckin) {
       this.codigo = codigo;
       this.hospede = hospede;
       this.dataCheckin = dataCheckin;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Hospede getHospede() {
        return this.hospede;
    }
    
    public void setHospede(Hospede hospede) {
        this.hospede = hospede;
    }
    public Date getDataCheckin() {
        return this.dataCheckin;
    }
    
    public void setDataCheckin(Date dataCheckin) {
        this.dataCheckin = dataCheckin;
    }




}


