package Model;
// Generated 18/11/2014 01:42:29 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Checkout generated by hbm2java
 */
public class Checkout  implements java.io.Serializable {


     private int codigo;
     private Hospede hospede;
     private Date dataCheckout;
     private Reserva reserva;
     private Integer periodo;
     private Servico servico;
    public Checkout() {
    }

	
    public Checkout(int codigo) {
        this.codigo = codigo;
    }
    public Checkout(int codigo, Hospede hospede, Date dataCheckout) {
       this.codigo = codigo;
       this.hospede = hospede;
       this.dataCheckout = dataCheckout;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Hospede getHospede() {
        return this.hospede;
    }
    
    public void setHospede(Hospede hospede) {
        this.hospede = hospede;
    }
    public Date getDataCheckout() {
        return this.dataCheckout;
    }
    
    public void setDataCheckout(Date dataCheckout) {
        this.dataCheckout = dataCheckout;
    }

    /**
     * @return the reserva
     */
    public Reserva getReserva() {
        return reserva;
    }

    /**
     * @param reserva the reserva to set
     */
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }

    /**
     * @return the periodo
     */
    public Integer getPeriodo() {
        return periodo;
    }

    /**
     * @param periodo the periodo to set
     */
    public void setPeriodo(Integer periodo) {
        this.periodo = periodo;
    }

    /**
     * @return the servico
     */
    public Servico getServico() {
        return servico;
    }

    /**
     * @param servico the servico to set
     */
    public void setServico(Servico servico) {
        this.servico = servico;
    }




}


