package Model;
// Generated 18/11/2014 01:42:29 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Hospede generated by hbm2java
 */
public class Hospede  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private String cpf;
     private Set checkouts = new HashSet(0);
     private Set consumoServicos = new HashSet(0);
     private Set reservas = new HashSet(0);
     private Set statuses = new HashSet(0);
     private Set checkins = new HashSet(0);

    public Hospede(){}
    
    public Hospede(int codigo) {
        this.codigo = codigo;
    }
    public Hospede(int codigo, String nome, String cpf, Set checkouts, Set consumoServicos, Set reservas, Set statuses, Set checkins) {
       this.codigo = codigo;
       this.nome = nome;
       this.cpf = cpf;
       this.checkouts = checkouts;
       this.consumoServicos = consumoServicos;
       this.reservas = reservas;
       this.statuses = statuses;
       this.checkins = checkins;
    }

    
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public Set getCheckouts() {
        return this.checkouts;
    }
    
    public void setCheckouts(Set checkouts) {
        this.checkouts = checkouts;
    }
    public Set getConsumoServicos() {
        return this.consumoServicos;
    }
    
    public void setConsumoServicos(Set consumoServicos) {
        this.consumoServicos = consumoServicos;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }
    public Set getStatuses() {
        return this.statuses;
    }
    
    public void setStatuses(Set statuses) {
        this.statuses = statuses;
    }
    public Set getCheckins() {
        return this.checkins;
    }
    
    public void setCheckins(Set checkins) {
        this.checkins = checkins;
    }




}


